services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    image: app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - upload_data:/data/uploads
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=highlevel
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  upload_data:
