services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile.api
    image: api
    ports:
      - "3000:3000"
    volumes:
      - .:/src
      - upload_data:/data/uploads
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    depends_on:
      - postgres
      - redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    image: worker
    volumes:
      - .:/src
      - upload_data:/data/uploads
    environment:
      - NODE_ENV=development
      - DB_SYNC=false
    restart: unless-stopped
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:17
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=highlevel
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  upload_data:
  redis_data:
