services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    image: app
    ports:
      - "3000:3000"
    volumes:
      - ".:/app"
      - "/app/node_modules"
    environment:
      - NODE_ENV=development
    restart: unless-stopped

  postgres:
    image: postgres:17
    container_name: postgres
    restart: unless-stopped
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
